### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by Albertino2020** [ioanniskousis/positioning#1]
Hey team, @alishabab  and @ioanniskousis!

I appreciate your job and am learning a lot with it. You are going at a very high speed, guys!

This is not properly an issue, it is a congratulation!

Anyway, it would be fine if you could remove all files that are not associated with the project and put it in the .gitignore, and please update the README file.
Keep going.

**Comment by ioanniskousis** [comment]
We have solved these issues
We also have added gitignore and updated the README
